name: CI

on:
  # 手動運行工作流程（workflow_dispatch 事件觸發器配置後可以在actions下手動運行工作流）
  workflow_dispatch:
  push:
    branches: 
      - gh-pages
jobs:
  # jobs的id
  build-and-deploy:
    # 指定伺服器的運行環境：最新版本ubuntu
    runs-on: ubuntu-latest
    steps:
      # 使用actions/checkout@v4 庫拉取代碼到 ubuntu 上
      - name: Checkout
        uses: actions/checkout@v4

      # 安裝 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 打包成靜態文件
      - name: Build
        run: pnpm install && pnpm build